### ISSUE TITLE
Error when placing a RoboTank in the map editor

### ISSUE THREAD

**Issue by rawrfisher** [smcpeak/factorio-robotank#1] opened 2019-03-08 03:29 UTC
I keep getting some unrecoverable error when placing a robo tank in map editor.

Error while running event RoboTank::on_built_entity (ID 6)
__RoboTank__/control.lua:135: attempt to index field 'force_to_controllers' (a nil value)
stack traceback:
	__RoboTank__/control.lua:135: in function 'add_entity'
	__RoboTank__/control.lua:1189: in function <__RoboTank__/control.lua:1185>

This is the error in question

Edit:  Just had same error pop up when placing a logistic cart.  Gonna keep testing things

**Comment by smcpeak** [comment] 2019-04-03 01:45
Sorry for the slow reply!  Github wasn't sending notifications for new issues.  I think I have fixed that.

Anyway, I was able to reproduce this crash in RoboTank 0.4.0.  It seems to be caused by the same underlying bug as the one I just fixed in 0.4.2, namely that I can't wait for on_tick to initialize certain data structures.  I am going to close this since I think it is fixed, but please try with 0.4.2 and reopen if you see the same or a very similar crash (e.g., in add_entity).  (File another issue if a different crash or problem happens.)

**Closed as completed by smcpeak** 2019-04-03 01:45 UTC
